### ISSUE TITLE
Условные обозначения

### ISSUE THREAD

**Issue by simgislab** [nextgis/oralhistory#6]
Группа 1: Наземные объекты (капля)

водоем – СИНИЙ 
ландшафт (парки и проч.) – ЗЕЛЕНЫЙ
памятник – КРАСНЫЙ
строение - ОРАНЖЕВЫЙ
улица – ЖЕЛТЫЙ
зона (сюда все крупные территориальные образования: рынок, свалка, площадь, аэродром, спортивные площадки и пр.) – СВЕТЛО-СЕРЫЙ
село-деревня-поселок городского типа-дача (все выделяемые административные образование крупнее района) – ТЕМНО-СЕРЫЙ
район – СЕРЫЙ
другое – ЧЕРНЫЙ

Группа 2: Подземные объекты (ромб)

метро – ОРАНЖЕВЫЙ
"метро-2” – КРАСНЫЙ
другие подземные объекты - СЕРЫЙ

**Comment by rendrom** [comment]
Предлагаю в properties записей передавать `color: string` и `shape: 'circle' | 'brill' | 'rect' | 'marker'`

**Comment by rendrom** [comment]
`'circle' | 'brill' | 'rect' | 'marker' | 'star' | 'asterisk' | 'triangle'`

**Comment by simgislab** [comment]
окончательная классификация здесь
https://docs.google.com/spreadsheets/d/1qU_ezClPS36IXsrn4uNPFDmc_wE4TFhj3P-h1-qqpCA/edit#gid=1100677253

база данных к классификации приведена
